### ISSUE TITLE
Release v0.1 : TODO

### ISSUE THREAD

**Issue by jpec** [jpec/Qfacture#12]
Avant de publier la version 0.1, il me reste à finaliser le script d'installation et mettre à jour le fichier SQL.

**Comment by K-Phoen** [comment]
Ça avance ? =)

**Comment by jpec** [comment]
:)

Je fais ça d'ici ce weekend!
(ce soir c'est installation d'OpenBSD sur mon desktop)

**Comment by jpec** [comment]
Tu m'as doublé pour les *.sql :)
Je fais le script de compilation / installation ce soir.

**Comment by jpec** [comment]
C'est fait et publié.
Test sur Archlinux : OK.
Test sur Ubuntu / Debian : **TODO**.

**Comment by jpec** [comment]
Test sur Ubuntu : OK.

**Comment by K-Phoen** [comment]
kew kewl kewl =P

De mon côté j'ai un tout petit peu avancé sur la version 1.0 (pas des masses de temps en ce moment)

**Comment by jpec** [comment]
Release v0.1 done! 

http://github.com/jpec/Qfacture/tree/v0.1
