### ISSUE TITLE
v1.0 : Analyse/Création de l'architecture

### ISSUE THREAD

**Issue by jpec** [jpec/Qfacture#13]
Analyse pour concevoir l'architecture MVC et le diagramme des classes.

**Comment by jpec** [comment]
J'ai vu que tu as commencé les diagrammes. Tu utilises quoi comme logiciel?

**Comment by K-Phoen** [comment]
J'utilise Dia.

On a un début de diagramme de classes qui décrit les entités (clients, produits, factures & co) et le big contrôleur qui fera le lien avec la GUI.

Ce diagramme n'est évidemment pas complet ni totalement juste (déjà il n'y a pas les évènements), c'est juste un point de départ =p
