### ISSUE TITLE
Bad sql for mysql 5.1.49-1

### ISSUE THREAD

**Issue by tclavier** [jpec/Qfacture#15]
With mysql 5.1.49-1, and last head of git, i have that when i launch Qfacture : 

QSqlQuery::value: not positioned on a valid record
QSqlQuery::value: not positioned on a valid record
QSqlQuery::value: not positioned on a valid record
QSqlQuery::value: not positioned on a valid record
QSqlQuery::value: not positioned on a valid record
QSqlQuery::value: not positioned on a valid record
QSqlQuery::value: not positioned on a valid record
QSqlQuery::value: not positioned on a valid record
QSqlQuery::value: not positioned on a valid record
QSqlQuery::value: not positioned on a valid record

And i see 0 table in database. How can i debug ? i had test "-h" "--help" "-v" "--verbose" and nothing work.

**Comment by jpec** [comment]
Je vais y regarder dans la soirée.

**Comment by jpec** [comment]
As tu bien suivi le wiki pour configuré mysql (création d'un utilisateur qui a tous les droits sur une base de donnée "qfacture_db") et puis chargé le dump : http://github.com/jpec/Qfacture/blob/master/qfacture_create_database.sql ?

C'est un problème avec la base...

**Comment by jpec** [comment]
Mis à jour le wiki.
Voir issue http://github.com/jpec/Qfacture/issues#issue/16.
