### ISSUE TITLE
Mauvaise configuration de la base de données ?

### ISSUE THREAD

**Issue by Numeriande** [jpec/Qfacture#16]
Impossible de tester quoique ce soit, rien ne s'enregistre. J'ai déjà galéré quelques heures pour tout installer, mais là je sèche.
Y a-t-il qqe chose qui cloche dans le retour que me fait qfacture_create_database.sql ?
Merci de votre aide.

mysql  Ver 14.14 Distrib 5.1.41, for debian-linux-gnu (x86_64) using readline 6.1
Copyright 2000-2008 MySQL AB, 2008 Sun Microsystems, Inc.
...
Variables (--variable-name=value)
and boolean options {FALSE|TRUE}  Value (after reading options)

---

auto-rehash                       TRUE
character-sets-dir                (No default value)
column-type-info                  FALSE
comments                          FALSE
compress                          FALSE
debug-check                       FALSE
debug-info                        FALSE
database                          (No default value)
default-character-set             latin1
delimiter                         ;
vertical                          FALSE
force                             FALSE
named-commands                    FALSE
ignore-spaces                     FALSE
local-infile                      FALSE
no-beep                           FALSE
host                              localhost
html                              FALSE
xml                               FALSE
line-numbers                      TRUE
unbuffered                        FALSE
column-names                      TRUE
sigint-ignore                     FALSE
port                              3306
prompt                            mysql> 
quick                             FALSE
raw                               FALSE
reconnect                         FALSE
socket                            /var/run/mysqld/mysqld.sock
ssl                               FALSE
ssl-ca                            (No default value)
ssl-capath                        (No default value)
ssl-cert                          (No default value)
ssl-cipher                        (No default value)
ssl-key                           (No default value)
ssl-verify-server-cert            FALSE
table                             FALSE
user                              qfacture
safe-updates                      FALSE
i-am-a-dummy                      FALSE
connect_timeout                   0
max_allowed_packet                16777216
net_buffer_length                 16384
select_limit                      1000
max_join_size                     1000000
secure-auth                       FALSE
show-warnings                     FALSE

**Comment by jpec** [comment]
Essayez la commande suivante :
    cd repertoire_qui_contient_le_fichier_sql
    mysql -h localhost -u root -p < qfacture_create_database.sql
Vous devez ensuite renseigner le mot de passe root de mysql.
Ensuite donnez tous les privilèges à votre utilisateur sur la base qfature_db.

**Comment by jpec** [comment]
Mis à jour le wiki.

**Comment by Numeriande** [comment]
Impeccable merci.
Les procédures d'installations sont très insuffisamment renseignées pour les apprentis linuxiens, mais bon c'est la version 0.1 et merci de nous en faire déjà profité.
