### ISSUE TITLE
v0.1 : Retours de Fabrice (à trier et statuer)

### ISSUE THREAD

**Issue by jpec** [jpec/Qfacture#19]
Joli logo pour Qfacture.
J'apprécie le design simple mais "propre", ordonné et la facilité de prise en main, "d'intuitivité" légère.
Le sentiment d'ensemble qui en ressort c'est : agréable à utiliser.

CLIENT
• J'apprécierai que lorsque je clique sur le bouton NOUVEAU le curseur se positionne automatiquement dans la case du nom à remplir, ou au moins que la touche TAB y amène directement (clients et prestations)
• Quelques touches de raccourcis seraient les bienvenues pour les aficionados du clavier  : au moins pour ENREGISTRER et NOUVEAU
• Piège : Après avoir supprimé un client j'ai accès aux cases pour en saisir un autre sans avoir appuyé sur le bouton NOUVEAU... mais pas au bouton ENREGISTRER. Et quand j'appuie sur NOUVEAU, ça efface tout ce que je viens de saisir.
• Lorsqu'on appuie sur ENREGISTRER on a toujours accès au bouton NOUVEAU qui peut tout effacer la saisie en cours.
• Un champ INTERLOCUTEUR par client serait le bienvenu, de même q'un champ MODE DE RÈGLEMENT PREFERE.
MERCI
• J'apprécie qu'aucun élément ne soit obligatoire pour enregistré un nouveau client

FACTURE
• Le numéro de facture est une gestion souvent très personnalisée. Vous imposez un numéro (invisible lors de la saisie). Pourquoi ne pas laisser le champ à saisir ou proposer de définir avec l'utilisateur un format (dans des préférences par exemple) ? Gardez un autre numéro d'enregistrement pour la gestion sql de l'enregistrement et offrez un autre numéro à l'utilisateur pour sa gestion à lui par exemple.
• Saisie du client : En complément de la liste, un champ de recherche plein texte (nom, adresse...) serait bienvenu pour ceux qui ont plus de 15 clients.
• J'aimerai indiquer, pour moi, un prix de base pour les prestations mais pouvoir modifier directement le prix unitaire dans la ligne de facture (sans passer par une remise)
• J'apprécierai de pouvoir modifier dans la facture le commentaire de la prestation pour l'adapter à la facture en cours d'édition.
• J'apprécierai de proposer moi-même à mes clients le type de règlement (ou plusieurs ?) pour la facture. Les types de règlement doivent être ouverts et paramétrables.
• Un commentaire est indiqué comme dernière colonne de la liste des factures. Où peux-t-on le saisir ?

FACTURE EN IMPRESSION
• BUG PRIORITAIRE : La facture reprend le bon nombre de lignes de prestations mais affiche toujours la même première ligne en duplicata (la première ligne de prestation saisie).
• La date de la facture n'est pas au format français sur le PDF
• Le numéro de facture n'est pas assez visible. On ne sait même pas à première vu que c'est une facture (pour celui qui la reçoit). Personnellement, je le verrai bien plus gros, gras et centré (à la hauteur où il est déjà)
• A mon sens, la désignation devrait reprendre le "commentaire" saisit pour la prestation et pas le nom (idem en saisie de la facture). Revoir dans ce cas les colonnes pour laisser un moins la moitié de la page au commentaire et la deuxième moitie aux 3 colonnes de chiffres
• Le N° SIRET est imprimé dans l'entête et dans le pied de page, est-ce voulu, utile  ?
• C'est quoi la blague du RIB sur la facture ? Où le renseigner ?
• ET la blague du cope APE ?  D'où sort-il ?
• Inutile de faire remarquer à tout le monde que je n'ai pas de site internet (si ce n'est pas renseigné, la rubrique "site internet :" apparaît quand même en bas de la facture). Personnellement, j'allègerai la facture en retirant les intitulés "Téléphone : ", "Site internet :" et "E-mail :"
• On a souvent besoin d'afficher des commentaires particuliers administratifs ou promotionnels sur une facture (Les frais en cas de retard, la promo du mois ou le slogan de son entreprise...). Pourquoi ne pas ajouter 1 ou 2 champs libres facultatifs  (à renseigner dans les préférences) à imprimer sur la facture (un en entête et un en pied de page) ?
MERCI
• J'apprécie de pouvoir utiliser une prestation à 0, cela permet d'ajouter des commentaires dans le corps de la facture (date de la prestation)
• J'apprécie de pouvoir double-cliquer n'importe où sur la ligne de la prestation pour la sélectionner.
• J'apprécie le tri possible sur chaque entête de colonne
• J'apprécie les factures au format PDF dès la version 0.1 !

STATISTIQUES
• Merci pour les statistiques dès la version 0.1. Elles sont, j'imagine, prévues pour calculer les cotisations à payer chaque mois ou trimestre, sauf que : Les cotisations doivent être calculées sur les RECETTES, c'est à dire sur l'argent réellement entré et non pas sur les factures émises. Il peut y avoir un gros décalage entre l'émission de la facture et le paiement. Il serait donc souhaitable de saisir pour chaque facture la date de règlement et de calculer les stats en conséquence.
• Sans partir dans une gestion des relances, un gros plus serait de faire le total de l'argent encore dehors (factures impayées), c'est très motivant et c'est souvent un point faible des artisans.

PARAMETRES
• Pourrions-nous avoir un champ INTERLOCUTEUR en plus de la raison sociale ? C'est une auto-entreprise, je sais, mais certains clients me connaisse sous le nom de l'entreprise et d'autres sous mon nom propre.
• Il manque le RIB.
• Il manque le Code APE.

PREFERENCES
Il va rapidement falloir créer des préférences pour régler des options :
• Affichage ou non du RIB sur la facture
• Chemin de sauvegarde des factures en PDF
• Pourquoi pas les libellés des entêtes de colonne  pour les factures pour permettre de personnalisé selon le métier de chacun. Personnellement je mettrais bien "Nb Heures" plutôt que "quantité".

**Comment by K-Phoen** [comment]
Il y a pas mal de choses que j'avais prévu d'ajouter/corriger dans la prochaine version. On peut certainement en backporter quelques unes dans la version courante.

Je commence à croire que l'issue tracker de github est quasi inutile tellement il est limité en fonctionnalités. On pourrait pas envisager de migrer vers du Redmine/autre ? (je peux héberger au besoin)

**Comment by jpec** [comment]
> CLIENT
> • J'apprécierai que lorsque je clique sur le bouton NOUVEAU le
> curseur se positionne automatiquement dans la case du nom à remplir,
> ou au moins que la touche TAB y amène directement (clients et
> prestations) 

C'est fait!

> • Quelques touches de raccourcis seraient les bienvenues
> pour les aficionados du clavier  : au moins pour ENREGISTRER et
> NOUVEAU 

C'est fait (survoler les boutons pour voir les raccourcis).

> • Piège : Après avoir supprimé un client j'ai accès aux cases
> pour en saisir un autre sans avoir appuyé sur le bouton NOUVEAU...
> mais pas au bouton ENREGISTRER. Et quand j'appuie sur NOUVEAU, ça
> efface tout ce que je viens de saisir. 

C'est corrigé !

> • Lorsqu'on appuie sur
> ENREGISTRER on a toujours accès au bouton NOUVEAU qui peut tout
> effacer la saisie en cours. 

C'est corrigé !

> • Un champ INTERLOCUTEUR par client
> serait le bienvenu, de même q'un champ MODE DE RÈGLEMENT PREFERE.

_À voir pour l'ajouter dans la version 1.0 (nécessite une
restructuration de la base de donnée)._

> FACTURE
> • Le numéro de facture est une gestion souvent très personnalisée.
> Vous imposez un numéro (invisible lors de la saisie). Pourquoi ne pas
> laisser le champ à saisir ou proposer de définir avec l'utilisateur
> un format (dans des préférences par exemple) ? Gardez un autre numéro
> d'enregistrement pour la gestion sql de l'enregistrement et offrez un
> autre numéro à l'utilisateur pour sa gestion à lui par exemple. 

_À voir pour l'ajouter dans la version 1.0 (nécessite une
restructuration de la base de donnée)._

> • Saisie du client : En complément de la liste, un champ de recherche
> plein texte (nom, adresse...) serait bienvenu pour ceux qui ont plus
> de 15 clients. 

_On en avait déjà parlé avec Kévin... Ce sera pour la version 0.3._

> • J'aimerai indiquer, pour moi, un prix de base pour
> les prestations mais pouvoir modifier directement le prix unitaire
> dans la ligne de facture (sans passer par une remise) 

_À statuer._ 

> • J'apprécierai
> de pouvoir modifier dans la facture le commentaire de la prestation
> pour l'adapter à la facture en cours d'édition. 

_Faisable, v0.1.3?_

>  • J'apprécierai de
> proposer moi-même à mes clients le type de règlement (ou plusieurs ?)
> pour la facture. Les types de règlement doivent être ouverts et
> paramétrables. 

Voir modification template facture (nouvel onglet depuis v0.1.2).

> • Un commentaire est indiqué comme dernière colonne de
> la liste des factures. Où peux-t-on le saisir ?

_Fonctionnalité prévue mais non implémentée (ce sera pour la v0.1.3)._ 

> FACTURE EN IMPRESSION
> • BUG PRIORITAIRE : La facture reprend le bon nombre de lignes de
> prestations mais affiche toujours la même première ligne en duplicata
> (la première ligne de prestation saisie). 

Corrigé (v0.1.1).

> • La date de la facture n'est pas au format français sur le PDF 

_Ce sera pour la v0.1.3._ 

• Le numéro de facture n'est

> pas assez visible. On ne sait même pas à première vu que c'est une
> facture (pour celui qui la reçoit). Personnellement, je le verrai
> bien plus gros, gras et centré (à la hauteur où il est déjà) 

Il faut que l'utilisateur ajuste son template de facture (voir nouvel
onglet depuis v0.1.2).

> • A mon sens, la désignation devrait reprendre le "commentaire"
> saisit pour la prestation et pas le nom (idem en saisie de la
> facture). Revoir dans ce cas les colonnes pour laisser un moins la
> moitié de la page au commentaire et la deuxième moitie aux 3 colonnes
> de chiffres 

_À statuer pour ajouter une ligne commentaire par article dans la
facture... v0.1._ ou v1.0?\* 
Pour la taille des colonnes, voir template.

> • Le N ° SIRET est imprimé dans l'entête et dans le pied
> de page, est-ce voulu, utile  ? 

Oui.

> • C'est quoi la blague du RIB sur la facture ? Où le renseigner ? 

Cf template.

> • ET la blague du cope APE ?  D'où sort-il ? 

Cf template.

> • Inutile de faire remarquer à tout le monde que je n'ai
> pas de site internet (si ce n'est pas renseigné, la rubrique "site
> internet :" apparaît quand même en bas de la facture).
> Personnellement, j'allègerai la facture en retirant les intitulés
> "Téléphone : ", "Site internet :" et "E-mail :" 

Cf template.

> • On a souvent besoin
> d'afficher des commentaires particuliers administratifs ou
> promotionnels sur une facture (Les frais en cas de retard, la promo
> du mois ou le slogan de son entreprise...). Pourquoi ne pas ajouter 1
> ou 2 champs libres facultatifs  (à renseigner dans les préférences) à
> imprimer sur la facture (un en entête et un en pied de page) ? MERCI

C'est le commentaire facture (non implémenté pour l'instant).

> STATISTIQUES
> • Merci pour les statistiques dès la version 0.1. Elles sont,
> j'imagine, prévues pour calculer les cotisations à payer chaque mois
> ou trimestre, sauf que : Les cotisations doivent être calculées sur
> les RECETTES, c'est à dire sur l'argent réellement entré et non pas
> sur les factures émises. Il peut y avoir un gros décalage entre
> l'émission de la facture et le paiement. Il serait donc souhaitable
> de saisir pour chaque facture la date de règlement et de calculer les
> stats en conséquence. 

_Pour v1.0 (restructuration)_  

> • Sans partir dans une gestion des relances, un
> gros plus serait de faire le total de l'argent encore dehors
> (factures impayées), c'est très motivant et c'est souvent un point
> faible des artisans.

_Voir pour v0.1.3?_

> PARAMETRES
> • Pourrions-nous avoir un champ INTERLOCUTEUR en plus de la raison
> sociale ? C'est une auto-entreprise, je sais, mais certains clients
> me connaisse sous le nom de l'entreprise et d'autres sous mon nom
> propre. 

_Voir pour la version v1.0._ 

> • Il manque le RIB. • Il manque le Code APE.

_Voir pour la version v1.0._

> PREFERENCES
> Il va rapidement falloir créer des préférences pour régler des
> options : • Affichage ou non du RIB sur la facture
> • Chemin de sauvegarde des factures en PDF
> • Pourquoi pas les libellés des entêtes de colonne  pour les factures
> pour permettre de personnalisé selon le métier de chacun.
> Personnellement je mettrais bien "Nb Heures" plutôt que "quantité".

_Voir pour la version v1.0._

**Comment by jpec** [comment]
Toutes les modifications faisables en v0.1.\* sont prises en compte.
Pour les autres modifications, ce sera pour la v1.0.
