### ISSUE TITLE
Conserver la base de données

### ISSUE THREAD

**Issue by Numeriande** [jpec/Qfacture#22]
Merci pour la réactivité de ces releases.
Mais comment puis-je faire pour installer ces nouvelles versions (j'ai utilisé install.sh) et que ma base de données ne soit pas réinitialisée ?!
Ma deuxième question recoupe un peu la première : comment sauvegarder la base de données de Qfacture ? Où Mysql range-t-il ses petites affaires ?
Désolé pour ces questions qui vous sembleront peut-être basiques, mais vous l'avez compris je suis un nouveau converti à Linux et j'ai encore besoin qu'on me guide par la main.
Merci.

**Comment by jpec** [comment]
En effet le nouveau script install.sh initialise la BD. Pour éviter ceci, au moment ou il demande le user de la base mysql il suffit de faire un "Ctrl+C" (kill process).

Pour faire une sauvegarde de la base de donnée : la façon la plus simple est d'utiliser le client mysql en CLI :

```
mysqldump -A --user='root' --password='mot de passe utilisateur root de MYSQL' > dump_$(date +'%F').sql
```

Il est préférable d'utiliser l'utilisateur root pour la sauvegarde car lui seul permet de sauvegarder les privilèges de la BD (users/password/etc.). 

Après, il suffit d'ajouter cette commande dans crontab pour la planifier tous les soirs par exemple.

**Comment by Numeriande** [comment]
Merci.
Apparemment ça marche.
