### ISSUE TITLE
V1.0 : Feature - Séparation onglet Liste des factures / Facture

### ISSUE THREAD

**Issue by jpec** [jpec/Qfacture#28]
Je propose de remanier l'onglet Factures :
avoir un onglet fixe Liste des factures/devis,
ouvrir chaque facture dans un nouvel onglet (possible grâce à la création des onglets à la volée).

Sur l'onglet Liste des factures / devis, on aura uniquement :
la liste des factures / devis,
les boutons "Actions" (Ouvrir, Nouvelle).

Sur l'onglet Facture, on aura :
les champs de la facture (classiques),
les boutons "Actions" (Sauver, Imprimer, Supprimer, Fermer),
les boutons Fermer et Supprimer fermeront l'onglet,
le nom de l'onglet sera "Facture/Devis XXXXXXX".

Qu'en penses tu?

**Comment by K-Phoen** [comment]
C'est une bonne idée =)

**Comment by jpec** [comment]
Rapide!

**Comment by jpec** [comment]
Bon je vais m'attaquer à l'onglet liste des factures...

**Comment by K-Phoen** [comment]
"Rapide!" -> j'suis en cours de Merise, j'ai besoin de distractions ! :p

**Comment by jpec** [comment]
:)

Pourtant c'est bon des merises !!! 
=>[]
