### ISSUE TITLE
Supprimer une ligne article dans la facture ou devis

### ISSUE THREAD

**Issue by tonycab** [jpec/Qfacture#29]
Il serais assez assez intéressant de pouvoir supprimer une ligne article dans la facture ou devis. Cela éviterait de devoir refaire la facture à chaque erreurs. 

Compilé et testé sous Fedora 14 (Pas tenté d'utilisé le script bash pour l'install)

Je vous découvre dans Linux Pratique. Votre projet est très prometteur et je pense va intéresser beaucoup de monde.

**Comment by jpec** [comment]
C'est faisable, il suffit de mettre 0 en quantité et la ligne disparaît...

**Comment by K-Phoen** [comment]
Si tonycab ne l'as pas trouvé, c'est certainement que ce n'est pas assez intuitif. On fera mieux dans la prochaine version (avec par exemple une icône en forme de croix tout à droite de la ligne)
