### ISSUE TITLE
Possibility to use sqlite3

### ISSUE THREAD

**Issue by dolanor** [jpec/Qfacture#39]
Configuring a mysql just for a (nearly)single user application is overkill. Sqlite is less a pain I think.

**Comment by jpec** [comment]
I don't maintain Qfacture anymore.
I suggest you to fork Qfacture and adapt it to work with Sqlite (rename the
driver and adapt the db dump).

2013/7/3 dolanor notifications@github.com

> Configuring a mysql just for a (nearly)single user application is
> overkill. Sqlite is less a pain I think.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/jpec/Qfacture/issues/39
> .

## 

Julien PECQUEUR

Tél: 06.49.86.90.72
Mail: jpec80@gmail.com
