### ISSUE TITLE
Impossible de supprimer un client

### ISSUE THREAD

**Issue by jpec** [jpec/Qfacture#4]
Impossible de supprimer un client.
Impossible de charger un client dans le formulaire d'édition.
Il faut donc finaliser la table mise en place.

**Comment by jpec** [comment]
Je propose de ne pas éditer le client en direct sur la table mais de passer sur le formulaire comme avant. Ça permet d'éviter les saisies intempestives. Et résout le problème de la suppression.

**Comment by K-Phoen** [comment]
Normalement c'est réglé.

**Comment by jpec** [comment]
Ok je ferme le ticket alors! ;)
