### ISSUE TITLE
Feature: Génération facture PDF.

### ISSUE THREAD

**Issue by jpec** [jpec/Qfacture#6]
Implémenter la génération de la facture au format PDF "on the fly".

**Comment by jpec** [comment]
Prototype en cours.

**Comment by jpec** [comment]
Base mise a jour (voir patch).
Template html en cours (avec variables %logo% par exemple).
Par contre ce weekend j' ai pas eu de temps pour bosser dessus...

**Comment by jpec** [comment]
Bon j'abandonne l'idée du template html car c'est impossible de lier le logo avec une balise <img />...
Je vais essayer avec Qprinter... Par contre les templates seront plus compliqués à mettre en service!

**Comment by K-Phoen** [comment]
Autre idée : ne pas stocker du tout de logo dans la BDD mais juste son adresse sur le disque.

On peut très bien l'afficher dans l'interface via son adresse et pareil pour l'embed dans une facture.
T'en penses quoi ?

**Comment by jpec** [comment]
Le but de la base et de regrouper toutes les données de Qfacture (pas de répertoire perso). Par exemple chez moi j'ai ma base sur mon serveur perso et j'y accède depuis mon netbook ou mon desktop.
Par contre on peut exporter le logo au démarrage de Qfacture dans /tmp (ou plutôt le répertoire tmp de Qt4)? Qu'en penses tu?

**Comment by K-Phoen** [comment]
mon dernier commit ajoute un début de solution à ce problème. C'est très sommaire pour le moment, mais le code présent permet déjà de générer un PDF via un contenu de base décrit en HTML.

Je te laisse zieuter tout ça avant qu'on continue quoi que ce soit =)

**Comment by jpec** [comment]
Pour moi ca me va QPrinter et compagnie!

**Comment by jpec** [comment]
J'ai rajouté le nom du document généré pour ne pas l'oublier plus tard.

**Comment by K-Phoen** [comment]
La génération d'un PDF est (dans les grandes lignes) terminées. Je fais un modèle de facture de base et je ferme le ticket \o/

**Comment by jpec** [comment]
Je clôture le ticket! Le Template que tu as fait fonctionne parfaitement!
