### ISSUE TITLE
RoadMap: plans pour la version stable 1.0

### ISSUE THREAD

**Issue by jpec** [jpec/Qfacture#7]
Suite à la discussion d'hier avec K-phoen, on a décidé de repartir de zéro pour la version stable 1.0 de Qfacture. Nous allons donc juste terminer d'implémenter la génération de facture au format PDF pour la version 0.1 pour la rendre utilisable mais nous allons la laisser au stade de prototype.

La version 0.1 nous aura permis de valider certains points d'ergonomie et de découvrir les faiblesses d'autres.

Nous voulons concentrer nos efforts pour repenser l'architecture de Qfacture et la coder de manière propre afin d'améliorer la maintenabilité du code et faciliter le développement des futures fonctionnalités.

Nous gardons par contre la base de données actuelle pour pouvoir garder l'historique des factures déjà créées (seuls des modifications mineures seront effectuées - pas de pertes de données).

Nous utiliserons aussi différentes branches : master qui contient la version de prodution (actuellement la 0.1-alpha), testing qui contient la future version (alpha, beta puis release candidate et enfin devel).

**Comment by jpec** [comment]
On pourrait utiliser QtCreator pour la version 1.0. Ça permettrai d'avoir la même indentation, etc. et je le trouve super léger. 
Dis moi si QtCreator te plait.

**Comment by K-Phoen** [comment]
j'approuve le choix =P

**Comment by jpec** [comment]
La version de développement est dorénavant sur le dépôt Qfacture-testing
